# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch: {}
  push:
    paths:
      - '*.go'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: env GOOS=linux GOARCH=abd64 go build -o ./gpt-bot_amd64 -v ./...

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: gpt-bot_amd64
        path: ./gpt-bot_amd64

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ contains(github.event.head_commit.message, '[commit var]') }}
        body_path: readme.md
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gpt-bot_amd64
        asset_name: gpt-bot_amd64
        asset_content_type: application/octet-stream